# -*- coding: utf-8 -*-
"""Hungman Game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cea65ItIsa7Vb7i7aAwpdiLpelUAkjFA
"""

import random

def play_hangman():

    word_bank = ["python", "codealpha", "internship", "developer", "program"]
    secret_word = random.choice(word_bank)

    guessed_letters = []
    turns_left = 6

    print("=======================================")
    print("      Welcome to Hangman Game!    ")
    print("=======================================")
    print("Try to guess the secret word letter by letter.")
    print("You have 6 incorrect guesses allowed. Good luck!\n")

    while turns_left > 0:

        display_word = ""
        for letter in secret_word:
            if letter in guessed_letters:
                display_word += letter + " "
            else:
                display_word += "_ "

        print("Word progress: " + display_word)
        print("Turns remaining: " + str(turns_left))
        print("Letters you guessed: " + str(guessed_letters))
        print("-" * 40)

        if "_" not in display_word:
            print("CONGRATULATIONS! You guessed the word: " + secret_word)
            break

        guess = input("Guess a letter: ")
        guess = guess.lower().strip()


        if len(guess) != 1 or not guess.isalpha():
            print("[ERROR] Invalid input. Please enter a single alphabetical letter.\n")

        elif guess in guessed_letters:
            print("[WARNING] You already guessed the letter '" + guess + "'. Try a different one.\n")

        else:
            guessed_letters.append(guess)

            if guess in secret_word:
                print("CORRECT! '" + guess + "' is in the word.\n")
            else:
                print("INCORRECT! '" + guess + "' is not in the word.\n")
                turns_left -= 1

    if turns_left == 0:
        print("=======================================")
        print("GAME OVER! You ran out of turns.")
        print("The correct word was: " + secret_word)
        print("=======================================")

play_hangman()